version: '3'

services:
  course-service:
    build: ./courses
    volumes:
      - ./courses:/usr/src/app
    ports:
      - 7001:80

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 7000:80
    depends_on:
      - course-service
